


namespace OpcRcw.Hda
{
  public enum OPCHDA_UPDATECAPABILITIES
  {
    OPCHDA_INSERTCAP = 1,
    OPCHDA_REPLACECAP = 2,
    OPCHDA_INSERTREPLACECAP = 4,
    OPCHDA_DELETERAWCAP = 8,
    OPCHDA_DELETEATTIMECAP = 16, // 0x00000010
  }
}
